# Generated by Django 5.0.12 on 2025-02-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('link', models.URLField(primary_key=True, serialize=False)),
                ('link_imagem', models.URLField()),
                ('nome', models.CharField(max_length=255)),
                ('valor', models.IntegerField()),
                ('valor_com_desc', models.IntegerField()),
                ('pcto_desc', models.FloatField()),
                ('opcao_parc', models.CharField(blank=True, max_length=255, null=True)),
                ('full', models.BooleanField()),
                ('frete_gratis', models.BooleanField()),
                ('loja_oficial', models.BooleanField()),
            ],
            options={
                'db_table': 'produtos',
            },
        ),
    ]
